### ISSUE TITLE
I have a few questions about this API.

### ISSUE THREAD

**Issue by Louis345** [vincaslt/spaced-repetition#1]
I really appreciate you taking the time to make this App.

So, let's say I ask a user a question via a flash-card and the user responds that the question was hard to recall. Where do I go from there? Looking at your API, there is a config object how do I know what values to set it to? I guess I am a bit lost.  Like for example, ''bad': '5 minutes',  bad is set for 5 minutes? What does the 5 minutes represent?    Also,   'average': '5 days',   average is set for 5 days does that mean the user should be asked 5 days later, so I should store that in the database and do a check? Hopefully, my questions make a bit of sense.

**Comment by diego898** [comment]
bump!

**Comment by vincaslt** [comment]
It was designed to help automatically decide when to show words. Hence that number represents the time that the word is still fresh in user's memory (since I'd want to only show it when user is on the verge of forgetting it). It was not my intention to have the user tell whether he had trouble remembering the word or it was easy for him, rather you should deduce it from whether he answered correctly/quickly and set the status accordingly.

Where you store the results and current word's state is up to you, but I think it's best if that storage was persistent.
